<ul>

{{each(sec,section) sections}}
<!-- ${section.sectionName} -->
    {{each(idx,subsection) section.subsections}}
    <li>
    <a class="subsection{{if (section.subsections[idx].default)}} autoplay{{/if}}" href="?" id="target-${subsection.sectionId}">

    <span class="ui-silk inline ${subsection.sectionClass}"></span>
    ${subsection.sectionName}
    </a>
    </li>
    {{/each}}
<!-- // ${section.sectionName} -->
{{/each}}

</ul>