<div class="toolbar ui-widget">

<ul>

{{each(sec,section) sections}}
<!-- ${section.sectionName} -->
    {{each(idx,subsection) section.subsections}}
    <li>

<a class="subsection" href="?" id="target-${subsection.sectionId}" >
<span class="ui-silk inline ${subsection.sectionClass}"></span>
${subsection.sectionName}
</a>

    </li>
    {{/each}}
<!-- // ${section.sectionName} -->
{{/each}}

</ul>

</div>