{{each(sec,section) sections}}
    <h2{{if (section.meta)}} data-meta="${section.meta}"{{/if}}>
        <span class="textnode">${section.name}</span>
    </h2>
    <div>
        <ul>
        {{each(idx,subsection) section.subsections}}
            {{if (subsection.subsections && subsection.subsections.length > 0)}}
            <li class="submenu">
                <h3>
                    <a title="${subsection.name}{{if (subsection.description)}}: &lt;em&gt;${subsection.description}&lt;/em&gt;{{/if}}" class="subsection{{if (section.subsections[idx]['default'])}} autoplay{{/if}}">
                        <span class="ui-silk inline ${subsection.class}"></span>
                        <span class="textnode">${subsection.name}</span>
                    </a>
                </h3>
                <div>
                    <ul>
                        {{each(subidx,subsubsection) subsection.subsections}}
                        <li>
                            <a title="${subsubsection.name}{{if (subsubsection.description)}}: &lt;em&gt;${subsubsection.description}&lt;/em&gt;{{/if}}" class="subsection" {{if (subsubsection.meta)}} data-meta="${subsubsection.meta}"{{/if}} href="?" id="target-${subsubsection.id}">
                            <span class="ui-silk inline ${subsubsection.class}"></span>
                            <span class="textnode">${subsubsection.name}</span>
                            </a>
                        </li>
                        {{/each}}
                    </ul>
                </div>
            </li>
            {{else}}
            <li>
                <a title="${subsection.name}{{if (subsection.description)}}: &lt;em&gt;${subsection.description}&lt;/em&gt;{{/if}}" class="subsection{{if (section.subsections[idx]['default'])}} autoplay{{/if}}" {{if (subsection.meta)}} data-meta="${subsection.meta}"{{/if}} href="?" id="target-${subsection.id}">
                    <span class="ui-silk inline ${subsection.class}"></span>
                    <span class="textnode">${subsection.name}</span>
                </a>
            </li>
            {{/if}}
        {{/each}}
        </ul>
    </div>
{{/each}}
