<?php
        echo $this->render("main/header.phtml");
        echo $this->render("main/sidebar.phtml");
?>
	<div id="canvasWrapper">
	    <div id="canvas">
		    <div id="contenedorInterno">
			<?php
		        //if ($this->SiteConfig()->getLogo()):
		         //   echo '<img src="'.$this->baseUrl($this->SiteConfig()->getLogo()).'" alt="'.$this->SiteConfig()->getSiteName().'" />';
		        //endif;
		    ?>
			</div>
	        <ul class="tabs" id="tabsList"></ul>
        </div>
	</div>
<?php     
    echo $this->render("main/footer.phtml");
?>