<form title="${title}" action="" id="klearLogin">
{{if (error) }}
    <div class="ui-widget ui-corner-all ui-state-error loginError">
        <span class="ui-icon ui-icon-alert"></span>
        <p>${error}</p>
        
    </div>
{{/if}}
<div class="description ui-widget-content ui-corner-all">
<span class="ui-icon ui-icon-key"></span>
<p>${description}</p>

</div>
<input type="hidden" name="klearLogin" value="true" />
<p>
    <input id="username" autofocus="autofocus" type="text" name="username" />
    <label for="username"><?php echo $this->translate('User'); ?>:</label>
</p>

<p>
    <input id="password" type="password" name="password" />
    <label for="password"><?php echo $this->translate('Password'); ?>:</label>
</p>

<p class="submit"><input type="submit" value="<?php echo $this->translate('Authenticate'); ?>" /></p>


</form>