<!doctype html>
<html lang="<?php echo $this->SiteConfig()->getLang()->getLanguage();?>">
<head>
<?php


	$this->headTitle()->append("klear");
	$this->headTitle()->append($this->SiteConfig()->getYear());
	$this->headTitle()->prepend($this->SiteConfig()->getSiteName());
	$this->headTitle()->setSeparator(' :: ');

	echo $this->headTitle();
	echo "\n";
	echo $this->headMeta()
	->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
	->setName('viewport', 'width=device-width, initial-scale=1.0')
	->setIndent(4);
	echo "\n";

	// Este base antes que el script!!!
?>
    <base href="<?php echo $this->serverUrl($this->baseUrl('klear')); ?>/" />

<?php
	

	$this->headLink()
			->appendStylesheet($this->baseUrl('/klear/css/base/reset.css'))
			->appendStylesheet($this->baseUrl('/klear/css/base/layout.css'))
			->appendStylesheet($this->baseUrl('/klear/css/silk/silk-sprite.css'))
			->appendStylesheet($this->baseUrl('/klear/css-extended/silk-extended/silk-extended-sprite.css'))
			->appendStylesheet($this->SiteConfig()->getJQueryUItheme($this->baseUrl()))
			->appendStylesheet($this->baseUrl('/klear/css/base/klear.css'))
			->headLink(array('rel' => 'shortcut icon','href' => $this->baseUrl('/images/favicon.ico')))
			->setIndent(4);

	foreach ($this->SiteConfig()->getRawCss() as $_rawCss) {
        $this->headLink()->appendStylesheet($this->baseUrl($_rawCss));
    }

	echo $this->headLink();
	echo "\n";

	$this->headScript()
		->appendFile($this->baseUrl('klear/js/libs/yepnope.1.5.4-min.js'))
		->appendFile($this->baseUrl('klear/js/loader.js'))
		->setIndent(4);
	
	foreach ($this->SiteConfig()->getRawJavascripts() as $_rawJs) {
	    $this->headScript()->appendFile($this->baseUrl($_rawJs));
	}

	if ("development" === APPLICATION_ENV) {
	    $this->headScript()
	        ->appendFile($this->baseUrl('klear/js/plugins/jquery.translationRegister.js'))
	        ->setIndent(4);
	}

	echo $this->headScript();

	echo "\n";


?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body rel='<?php echo $this->baseUrl('klear')?>'>
<div id="wrapper">
    <div id="header">
        <div id="applicationLogo">
        <?php
        if ($this->SiteConfig()->getLogo()):
            echo '<img src="'.$this->baseUrl($this->SiteConfig()->getLogo()).'" alt="'.$this->SiteConfig()->getSiteName().'" />';
        endif;
        ?>
        </div>
        <div id="applicationInfo">
            <?php echo $this->Info()?>
        </div>
        <div id="applicationTools">

            <div id="headerToolsbar">

            	<input type="checkbox" id="tabsPersist" />

            	<label for="tabsPersist" title="<?php echo $this->translate("Remember opened main tabs.")?>">
            	    <span class="ui-icon ui-icon-unlocked" ></span>
            	</label>


            	<input type="checkbox" id="logout"
            	    data-url="<?php echo $this->url(array('controller' => 'index', 'action' => 'bye')) ?>"
            	/>
            	<label for="logout" title="<?php echo $this->translate("logout")?>">
            	    <span class="ui-icon ui-icon-power" ></span>
            	</label>

            </div>
            <div id="headerLanguagebar">
            <?php
            if ($langs = $this->SiteConfig()->getLangs()):
                if (sizeof($langs) > 1) {
                    echo '<span class="langSelector">';
                    foreach($langs as $_langIden => $lang) {
                        echo '<input type="radio" id="lang_'.$_langIden.'" value="'.$_langIden.'" name="lang" '.(($_langIden == $this->SiteConfig()->getLang()->getIden())? ' checked="checked"':'') .' /><label for="lang_'.$_langIden.'">'.$lang.'</label>';
                    }
                    echo '</span>';
                }
            endif;
            ?>
            </div>




        </div>
    </div>
<div id="body">
<div id="main">
