<!doctype html>
<html lang="<?php echo $this->SiteConfig()->getLang()->getLanguage();?>" <?php
    if ("development" === APPLICATION_ENV || "localdev" === APPLICATION_ENV) {
        echo ' data-stage="development"';
    }
?>>
<head<?php
if ($this->SiteConfig()->getDisableCDN()) {
    echo ' rel="noCDN"';
}
?>>
<?php
    if (!$this->SiteConfig()->getHideKlearName()) {
        $this->headTitle()->append("klear");
    }

    $this->headTitle()->append($this->SiteConfig()->getYear());
    if (APPLICATION_ENV!='production') {
        $this->headTitle()->append("ENV: " . APPLICATION_ENV);
    }
    $this->headTitle()->prepend($this->SiteConfig()->getSiteName());
    $this->headTitle()->setSeparator(' :: ');

    echo $this->headTitle();
    echo "\n";
    echo $this->headMeta()
        ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
        ->setName('viewport', 'width=device-width, initial-scale=1.0')
        ->setName('author', 'Irontec')
        ->setName('generator', 'Klear')
        ->setIndent(4);
    echo "\n";

    // Este base antes que el script!!!
?>
    <base href="<?php echo $this->serverUrl($this->baseUrl('klear')); ?>/" />

<?php
    $favIcon = $this->SiteConfig()->getFavIcon();
    if (trim($favIcon) == "") {
        $favIcon = 'images/favicon.ico';
    }

    $this->headLink()
            ->appendStylesheet($this->baseUrl('/klear/css/base/reset.css'))
            ->appendStylesheet($this->baseUrl('/klear/css/base/layout.css'))
            ->appendStylesheet($this->baseUrl('/klear/css/silk/silk-sprite.css'))
            ->appendStylesheet($this->baseUrl('/klear/css-extended/silk-extended/silk-extended-sprite.css'))
            ->appendStylesheet($this->SiteConfig()->getJQueryUItheme($this->baseUrl()),
                'screen', true, array('id' => 'currentTheme'))
            ->appendStylesheet($this->baseUrl('/klear/css/base/klear.css'))
            ->appendStylesheet($this->baseUrl('/klear/css/base/selectBoxIt.css'))
            ->appendStylesheet($this->baseUrl('/klear/css/base/print.css'), 'print')
            ->appendStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
            ->headLink(array('rel' => 'shortcut icon','href' => $this->baseUrl($favIcon)))
            ->setIndent(4);

    foreach ($this->SiteConfig()->getRawCss() as $_rawCss) {
        if (substr($_rawCss, 0, 2) == '//') {
            $this->headLink()->appendStylesheet($_rawCss);
        } else {
            $this->headLink()->appendStylesheet($this->baseUrl($_rawCss));
        }
    }

    echo $this->headLink();
    echo "\n";

    $this->headScript()
        ->appendFile($this->baseUrl('klear/js/libs/yepnope.1.5.4-min.js'))
        ->appendFile($this->baseUrl('klear/js/loader.js'))
        ->setIndent(4);

    foreach ($this->SiteConfig()->getRawJavascripts() as $_rawJs) {
        if (substr($_rawJs, 0, 2) == '//') {
            $this->headScript()->appendFile($_rawJs);
        } else {
            $this->headScript()->appendFile($this->baseUrl($_rawJs));
        }
    }

    echo $this->headScript();

    echo "\n";


?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body rel='<?php echo $this->baseUrl('klear')?>'>
<div id="wrapper">
    <div id="header">
        <div id="applicationLogo">
        <?php
        if ($this->SiteConfig()->getLogo()):
            echo '<img src="'.$this->baseUrl($this->SiteConfig()->getLogo()).'" alt="'.$this->SiteConfig()->getSiteName().'" />';
        endif;
        ?>
        </div>
        <div id="applicationInfo" data-rememberScroll="<?php echo $this->SiteConfig()->getRememberScroll();?>">
            <?php echo $this->Info()?>
        </div>
        <div id="applicationTools">

            <div id="headerToolsbar">
                <?php echo $this->Toolsbar();?>
            </div>
        </div>
    </div>
<div id="body">
<div id="main">
