<div id="sidebar">
<?php

    foreach ($this->menu() as $section) {
        echo '<h2>' . $section->getName() . '</h2>';
        echo '<div>';
        echo '<ul>';
        foreach ($section as $subsection) {
            echo '<li>';
            echo '<a class="subsection" href="?" id="target-'.$subsection->getMainFile().'" >';
            echo '<span class="ui-silk inline '.$subsection->getClass().'"></span>';
            echo $subsection->getName() . '</a>';
            echo '</li>';
        }

        echo '</ul>';
        echo '</div>';

    }

?>
</div>