<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Klear Application</title>
</head>
<body>
    <h1>Ha ocurrido un error</h1>

<?php if (APPLICATION_ENV == 'development'): ?>
    <h2><?php echo $this->message ?></h2>

    <h3>Exception information:</h3>
    <p><b>Message:</b> <?php echo $this->message; ?></p>
    <p><b>Code:</b> <?php echo $this->exceptionCode; ?></p>

    <h3>File:</h3>
    <pre><?php echo $this->file; ?> (line <?php echo $this->line; ?>)</pre>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->traceString; ?>
    </pre>

<?php else: ?>

    <h2>Póngase en contacto con el administrador para solucionarlo</h2>
    <p><b>Mensaje de error:</b> <?php echo $this->message; ?></p>
    <p><b>Código de error:</b> <?php echo $this->exceptionCode; ?></p>
<?php endif; ?>

</body>
</html>